services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
     - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    networks:
      - aws-local-vpc

networks:
  aws-local-vpc:
    name: aws-local-vpc
